name: CuboidPlugin
main: se.jeremy.minecraft.cuboid.Cuboid
author: enjikaka
website: http://minecraft.jeremy.se
version: 1.0

commands:
    cmod:
        description: Modify a cuboid
        usage: /<command>
    undo:
        description: Undo last command changes
        usage: /<command>
    protect:
        description: Protect a currently selected cuboid
        usage: /<command>
    cwalls:
        description: Builds walls for the selected cuboid
        usage: /<command> [material]
