name: Cuboid
main: se.jeremy.minecraft.cuboid.Cuboid
author: enjikaka
website: http://minecraft.jeremy.se
version: 0.0.1

commands:
    cmod:
        description: Modify a cuboid
        usage: /<command>
    undo:
        description: Undo last command changes
        usage: /<command>
    protect:
        description: Protect a currently selected cuboid
        usage: /<command>
    cwalls:
        description: Builds walls for the selected cuboid
        usage: /<command> <material>
    ccircle:
        description: Draws a circle on the ground with the specified block type
        usage: /<command> <radius> <material> [height]
    ccopy:
        description: Copy the selected cuboid
        usage: /<command>
    cdel:
        description: Removes all blocks within the cuboid.
        usage: /<command>
