name: CuboidPlugin
main: se.jeremy.minecraft.cuboid
author: enjikaka
website: http://minecraft.jeremy.se
version: 1.0

commands:
	cmod:
		description: modify a cuboid
		usage: /<command>
	undo:
		description: undo last command changes
		usage: /<command>
	protect:
		description: protect a currently selected cuboid
		usage: /<command>
