name: CuboidPlugin
main: me.furt.cuboidplugin.Main
version: 1.0
author: furt
database: false
description: Powerful plugin now for Bukkit, allowing ingame word editing and per-area features.
commands:
  cmod:
    description: modify a cuboid
    usage: /<command>
  undo:
    description: undo last command changes
    usage: /<command>
  protect:
    description: protect a currently selected cuboid
    usage: /<command>